### ISSUE TITLE
Support for multiple component sources

### ISSUE THREAD

**Issue by jedondfds** [seek-oss/playroom#101]
Currently in my `playroom.config.js`, I am only able to specify a single directory for my components:

```js
module.exports = {
  components: './components/src/',
...
}
```
However, it would be useful that I could point to a number of component sources by passing an array of paths like this:

```js
module.exports = {
  components: [
  './components/src/',
  './additional-components/src/'
 ],
...
}
```

**Comment by michaeltaranto** [comment]
We have achieved this by creating an explicit file for our playroom component exports. This allows us to inject additional or modified versions of our design system components, for example:

```ts
module.exports = {
  components: './playroom/components.ts',
}
```

```ts
// playroom/components.ts

export * from '../components/src';
export * from '../additional-components/src';
```

Checkout our example [in Braid](https://github.com/seek-oss/braid-design-system/blob/master/lib/playroom/components.ts).
