### ISSUE TITLE
[feature-request] Prettier... in-the-browser!

### ISSUE THREAD

**Issue by maraisr** [seek-oss/playroom#119]
**Feature request:** Have an auto-format, or format button that runs prettier over the code block in-the-browser!

If you're anything like me, you tend to do this; make code change, cmd+ctrl+l, cmd+s. Or in other terms, auto-format then save. Which has quite shamefully caused me to become a lazy developer.

~Most online based IDE-esk tools have a similar feature:~

- ~[Graphiql](https://github.com/graphql/graphiql/blob/0b1232373364b8d640017f753505c55fd23a8eb1/packages/graphiql/src/components/GraphiQL.js#L291-L295)~
> sorry, I thought most have it, but turns out neither, TypeScript playground, astexplorer or codepen have this feature 🤷‍♂ 

---

If ya'll agree to something like this, I'd be more than happy to attempt at raising a PR that add's this feature.

**Comment by markdalgleish** [comment]
It's already there, just hidden. Hit Cmd+S to format it, like you would in your editor.

**Comment by markdalgleish** [comment]
Worth thinking about how to make it less hidden though.

**Comment by maraisr** [comment]
maybe, ctrl+f as it auto-saves on every key-press?

But this is awesome, just tried it. I'm going to close this issue!!! Love the work!

**Comment by markdalgleish** [comment]
I went with Cmd+S because that's my muscle memory when using my normal editor. To your point, it doesn't actually trigger a save, but that didn't seem to matter much in practice..
