### ISSUE TITLE
make examples self contained…

### ISSUE THREAD

**Issue by kevinfoerster** [seek-oss/playroom#12]
for some odd reason i was not able to get playroom up and running, but i would love to use it.

unfortunatly, you cannot simply run the demos, which would be great to get a better understanding of playroom, could you update the example to be more or less ready to use

more like:
https://github.com/gatsbyjs/gatsby/tree/master/examples

**Comment by markdalgleish** [comment]
Closed by https://github.com/seek-oss/playroom/pull/2.
