### ISSUE TITLE
Trying out snippets

### ISSUE THREAD

**Issue by pascalduez** [seek-oss/playroom#120]
```js
// playroom.config.js

module.exports = {
  title: 'Playroom',
  outputPath: './dist',
  components: '...',
  snippets: './snippets/index.js',
};
```

```js
// ./snippets/index.js

import React from 'react';
import { Button } from '...';

export default [
  {
    group: 'Button',
    name: 'Test',
    code: <Button>Test</Button>,
  },
];
```

```
TypeError: snippet.split is not a function
```

**Comment by pascalduez** [comment]
`code: string` Where's the delete button? :)

**Comment by pascalduez** [comment]
Loving the feature! Thanks a bunch.

![Screenshot from 2020-02-04 16-21-41](https://user-images.githubusercontent.com/335467/73758452-ea3a0d80-476a-11ea-83f5-771b24cf3a7e.png)

**Comment by markdalgleish** [comment]
You could try something like this: https://github.com/algolia/react-element-to-jsx-string. We would have bundled it in with Playroom except that it can't handle all cases.

**Comment by roddds** [comment]
@markdalgleish can you give an example of the sort of thing react-element-to-jsx-string doesn't handle? I was just about to open an issue pointing that using it is a lot better than entering elements as strings, but now I'm afraid to continue down this path if it might cause problems in the future.

**Comment by pascalduez** [comment]
> can you give an example of the sort of thing react-element-to-jsx-string doesn't handle

@roddds All kind of render prop, render function for instance.  
And more.
