### ISSUE TITLE
feat: component & props listing

### ISSUE THREAD

**Issue by AndersDJohnson** [seek-oss/playroom#127]
Show a listing of all components and their props that you can point & click - this will enhance discoverability. I realize you can hit `<` to see components or space after `<MyComp ` to see props, but it's not as obvious. Existing autocomplete support is great but only goes so far if you don't know what to start typing (especially without fuzzy support #126).

**Comment by askoufis** [comment]
Thanks for the issue.

Playroom's editor is designed to show you appropriate suggestions as you write JSX. It's a bit unclear how/where we would show this list of components and/or props. I'm going to close this issue for now, but please feel free to re-open it with more specific details if this is still relevant to you.
