### ISSUE TITLE
Bug: Cursor jumps to start of code editor window on error

### ISSUE THREAD

**Issue by bradbarrow** [seek-oss/playroom#131]
I am trying my best to get a screen-capture of this happening.

Sometimes whilst coding in the `playroom` editor if I cause an error to be thrown (e.g. by using a variable that doesn't exist `<Button size={batm` as I type the `m` it'll throw an error (the frame will say "batm" is undefined) and my cursor jumps to the start of the editor. 

It doesn't always do this - and I'm not sure what conditions cause it. Sometimes I get errors like that and I can continue as normal, other times it jumps me around.

Posting here incase anyone else is able to re-create. (Have noted it happening on a number of engineers machines so it's not a messy local-environment thing).

**Comment by michaeltaranto** [comment]
Yes we're aware of the issue. It can also occur with rapid typing. The issue is one of a few problems we are facing with codemirror at the moment.

Thanks for logging, hopefully get to this soon.

**Comment by bradbarrow** [comment]
I don't know if this helps at all but I can confirm that I can reliable reproduce this by hitting backspace twice in quick succession. Other keys in quick succession don't reliably trigger this issue but a double backspace immediately sends my cursor to the top.

**Comment by michaeltaranto** [comment]
Yes that is the most common occurrence for me too. Thanks for the feedback.
