### ISSUE TITLE
Razzle with Sass 

### ISSUE THREAD

**Issue by icyJoseph** [seek-oss/playroom#133]
I am currently trying to use Sass with Razzle. It doesn't work out of the box, no problem. I pass `sass-loader` custom config, and then it complains about `jsx`, when I add the JSX loader, then I get:

```
 ERROR  Failed to compile with 1 errors                                                                                                                           11:09:51 AM

This dependency was not found:

* __PLAYROOM_ALIAS__COMPONENTS__ in ./node_modules/playroom/src/components.js

To install it, you can run: npm install --save __PLAYROOM_ALIAS__COMPONENTS__
```
This is the custom config I use:

```
webpackConfig: () => {
		return {
			module: {
				rules: [
					{
						test: /\.(js|jsx)$/,
						exclude: /node_modules/,
						use: {
							loader: 'babel-loader',
							options: {
								presets: ['@babel/preset-env', '@babel/preset-react']
							}
						}
					},
					{
						test: /\.s[ac]ss$/i,
						use: [
							// Creates `style` nodes from JS strings
							'style-loader',
							// Translates CSS into CommonJS
							'css-loader',
							// Compiles Sass to CSS
							'sass-loader'
						]
					}
				]
			}
		}
	}
```

**Comment by markdalgleish** [comment]
This error is because your JS loader is targeting Playroom's code. You need to exclude node modules from your loaders.

**Comment by icyJoseph** [comment]
You mean in the sass loader? the babel loader does have the `node_modules` exclude, and using in the sass loader didn't land it either. 

Btw, huge praise to you and everyone behind this project. First time I ran into any issue :)

**Comment by markdalgleish** [comment]
Sorry, misread the config. Might be worth ensuring all loaders are excluding node modules.

**Comment by icyJoseph** [comment]
I managed to fix this :) Deep in the sass I inherited there were faulty imports. Thanks again for this amazing tool!
