### ISSUE TITLE
iFrame opener

### ISSUE THREAD

**Issue by maraisr** [seek-oss/playroom#142]
Storybook has this button you can click that opens up the story's iframe in a new tab. Basically rips out the Storybook UI. Quite helpful for testing a component on a real device, without all the other things around it.

Could there be a feature within playroom to do just this. Id love to have my playroom in-browser editor, but allow me to open up that base64 thing on a real device. Without the playroom UI and things.

This could also mean that code-embeds could become a thing.

Thoughts?

**Comment by estesmax** [comment]
+1 for rendering the frame in the native context of the window. In my work I'm only operating on desktop sizes. I see why its great for some, but having the different frame sizes and padding around the frame hurts more than it helps in my line of work.

**Comment by marchamm** [comment]
+1 This would be a neat feature. 

As a workaround for testing natively on different devices we've found that viewing the source of the frame and then removing the `view-source:` solves some of that. This new view won't update when making changes in the editor. But it has helped us when creating and testing new components.

**Comment by michaeltaranto** [comment]
It's been something we have wanted to add for a while. Glad to hear others see value in it too! Hopefully have something to share soon

**Comment by michaeltaranto** [comment]
This should now be addressed with the new Preview feature available in `v0.17`

**Comment by maraisr** [comment]
YES IT IS!!!! THANK YOU SO MUCH!!! 💯
