### ISSUE TITLE
What to do after 'playroom:build'?

### ISSUE THREAD

**Issue by jacob-ruiz** [seek-oss/playroom#143]
Hi, sorry if this is a dumb question. What am I supposed to do after running "playroom:build"?

I see that it outputs a bunch of files to the output path ("./dist/playroom"), but I'm not sure what I need to do with these files to create a hosted playroom environment where other team members can simply visit a link and start using it.

Do you have a recommendation for steps to follow after running "playroom:build"?

Thanks for your help. I'm trying to get our design team to experiment with designing in JSX rather than in Figma, and this would be a huge help!

Great work on Playroom, I think it's really exciting for designers.

**Comment by BrunnerLivio** [comment]
For trying it out locally, you can easily run it with `playroom:start`. If you want to deploy it & you are fine with having a public server/Github, you can easily set it up with [Netlify](https://www.netlify.com) in 3-4 clicks.

Personally I use an nginx Docker container and publish that on an interal server using [Watchtower](https://github.com/containrrr/watchtower).

**Comment by jacob-ruiz** [comment]
Thanks for the quick reply. Will try the Netlify route. I was wanting to use Zeit Now, but wasn't sure how to deploy just the dist/playroom directory rather than my whole project. Looks like Netlify makes this pretty easy.

**Comment by BrunnerLivio** [comment]
@jacob-ruiz Once you have added your site to Netlify, just go to the "Edit Site > Build & deploy > Publish Directory" and set it to `dist/playroom` :)

**Comment by jacob-ruiz** [comment]
Thanks @BrunnerLivio. I tried setting "Publish Directory" to "dist/playroom" but the page loads blank. The console shows the following errors. 
<img width="1069" alt="Screen Shot 2020-04-06 at 7 44 37 PM" src="https://user-images.githubusercontent.com/3422246/78545411-17746c00-783f-11ea-8fe0-47ca28034919.png">
I'll try to troubleshoot some more on my own, but if you any ideas let me know. Thanks!

**Comment by BrunnerLivio** [comment]
@jacob-ruiz are you deploying the website on a subpath (e.g. `your-adress.com/playroom`) or on the root (e.g. `your-address.com`)? 
If you deploy it on the root path, then maybe try to regenerate the dist folder and deploy it again?

**Comment by jacob-ruiz** [comment]
@BrunnerLivio I linked my whole repo (a Next.js project) to Netlify, and then added "dist/playroom" under Build settings > Publish directory in Netlify.

URL: https://suspicious-bartik-622da6.netlify.com/
Github repo: https://github.com/jacob-ruiz/design-system-demo

**Comment by BrunnerLivio** [comment]
@jacob-ruiz Ah, remove the `baseUrl` setting and set the "Build command" to `playroom build` :)

**Comment by jacob-ruiz** [comment]
It worked! @BrunnerLivio big thanks for your help. Appreciate the persistence :)

In case anyone comes across this and has the same problem: The trick (aside from the other things already mentioned in this thread) was that build command in Netlify needs to be `playroom build`. I had written `playroom:build` instead, which was causing the deploy to fail. The Netlify deploy logs are a good place to check if you need to debug.

**Comment by michaeltaranto** [comment]
Sounds like this was resolved outside Playroom. Good work.
