### ISSUE TITLE
When on Chrome, zoom: 90%, iframe widths are sometimes buggy

### ISSUE THREAD

**Issue by adrienharnay** [seek-oss/playroom#144]
Hey,

How to reproduce:
- playroom.config.js: `widths: [320, 768, 1280]`
- on Chrome: CMD + - (zoom 90%)

The middle iframe's width will be 767.986 instead of 768.

Not sure if there's something playroom can do about it. If not, sorry about it and feel free to close the issue!

Cheers

**Comment by michaeltaranto** [comment]
Yeah unfortunately with browser zoom there is not much we can do here as we are at the mercy of the pixel rounding that occurs when you scale things down.
