### ISSUE TITLE
TypeScript Auto Complete

### ISSUE THREAD

**Issue by hipstersmoothie** [seek-oss/playroom#16]
It will be super helpful to have the props as autocomplete options. Something like VSCode's. You could probably even use there implementation since most of it is distributed as npm packages.

It should be able to work with:

- Plain old Prop Types
- Typescript (autocomplete would work amazing)

You could also use parse the JSDoc annotations to get descriptions for the props too.

If not an autocomplete interface it could as just live as another window that pops up and uses reactdocgen to make props table

**Comment by markdalgleish** [comment]
We currently have autocomplete of prop types, but we're looking into expanding this, particularly since we're moving towards TypeScript and don't want to rely on prop types. There'll hopefully be some movement here soon.

**Comment by hipstersmoothie** [comment]
Ah I'm using typescript so that's why I didn't see it.

**Comment by hipstersmoothie** [comment]
Is there a list of things needed for this? If possible I could contribute

**Comment by markdalgleish** [comment]
This is one we'll probably need to do internally, because we need to figure out how to cleanly integrate this into our own ecosystem.

**Comment by markdalgleish** [comment]
Closed by https://github.com/seek-oss/playroom/pull/35.
