### ISSUE TITLE
Is it possible to support components that lock focus?

### ISSUE THREAD

**Issue by jonambas** [seek-oss/playroom#160]
We have a few components, such as Modals and Drawers, that lock focus – using [react-focus-lock](https://github.com/theKashey/react-focus-lock). Focus jumps between frames and editing the code is impossible.

I'm not sure this is fixable in playroom, or if it even should be fixed, but wanted to call it out.
[See example](https://matchbox-playroom.netlify.app/#?code=N4Igxg9gJgpiBcIA8BZaBDANgAggBxgDsA+AHUO2yQCEIAPbAIwHMBeUkAdwAsBLAFxgdsediACsABkkcyFSlUYBXfvwgluMTHiQB6ZavVzKe2nTl60ULHJABfIA)

![Kapture 2020-05-26 at 10 15 56](https://user-images.githubusercontent.com/3903325/82911611-1bb52f80-9f3a-11ea-9470-5388aa4e731d.gif)

**Comment by maraisr** [comment]
How are you doing that? I ran your example, and when I <kbd>Tab</kbd> it stayed "locked" in the iFrame I was in. Which browser/OS are you using? It could be a Safari issue, touched on [in react-focus-lock](https://github.com/theKashey/react-focus-lock#focusing-in-osx-safarifirefox-is-strange).

![ezgif-5-7b6ae7a208d5](https://user-images.githubusercontent.com/599459/82981104-7fb92000-a02e-11ea-99ef-43c43c32a61b.gif)
> as you can see, I had to "click" on the button one preview over.

**Comment by jonambas** [comment]
Hmm I think my gif was taken in Safari, but I'm seeing the same behavior in chrome. I did find [this crossframe option though](https://github.com/reach/reach-ui/issues/536#issuecomment-614981674) in react-focus-lock. Will try this out, thanks!

**Comment by michaeltaranto** [comment]
This is more to do with the implementation of the `Modal`. `react-focus-lock` document how aggressive their lock is and provide mechanisms for disabling the lock. Have a play with the options and hopefully you'll find the recipe that works for your use case.

(We use `react-focus-lock` and [configured it for our use case](https://github.com/seek-oss/braid-design-system/blob/6eb982a5d14864d58460e2bd0f5161fc4e6d9751/lib/components/Dialog/Dialog.tsx#L200) and happy with it in Playroom — even with browsing snippets)

Closing this issue.
