### ISSUE TITLE
frameSrc was not found in __PLAYROOM_ALIAS__FRAME_COMPONENT__

### ISSUE THREAD

**Issue by maraisr** [seek-oss/playroom#164]
After the latest upgrade there seems to appear some warnings. The app still works however.

![image](https://user-images.githubusercontent.com/599459/83468518-5847d480-a4c0-11ea-8aef-4607936b3466.png)

---
node: v14.3.0
yarn: 1.22.4
playroom: 0.21.0
webpack: 4.43.0

**Comment by maraisr** [comment]
I don't think this 0.21.1 has solved the issue @mattcompiles 

![image](https://user-images.githubusercontent.com/599459/83704417-61b67580-a655-11ea-8810-818739596704.png)

![image](https://user-images.githubusercontent.com/599459/83704434-6b3fdd80-a655-11ea-9ec1-cdcbe49d4ffd.png)

**Comment by mattcompiles** [comment]
🤔 Hmm ok, will look into this next week.

**Comment by maraisr** [comment]
Thanks @mattcompiles! 💯  I've reverted back to 0.21.0 for now :)

**Comment by mattcompiles** [comment]
@maraisr I'm not seeing any issue on my end. Do you have a custom frame component? Also, can you ensure your custom webpack rules are not targeting playroom internals by mistake?

**Comment by maraisr** [comment]
Interesting. I mean to get typescript to work, you do need to run custom webpack loaders.

Re your point on targeting playroom internals, [I think I maybe have excluded that?](https://github.com/autoguru-au/overdrive/blob/master/playroom.config.js#L38)

But yeah, here are my config files:
- **Playroom.config.js**: https://github.com/autoguru-au/overdrive/blob/master/playroom.config.js
- **custom frame**: https://github.com/autoguru-au/overdrive/blob/master/.playroom/frame.tsx

**Comment by maraisr** [comment]
@mattcompiles looks like the issue can be solved by:

https://github.com/seek-oss/playroom/blob/dd8d0422673b74bf24436066d83647535a499bfa/src/Playroom/Frames/frameSrc.js#L11

```diff
- module.exports = frameConfig.frameSrc ? frameConfig.frameSrc : defaultFrameSrc;
+ export default frameConfig.frameSrc ? frameConfig.frameSrc : defaultFrameSrc;
```

which has worked for me. Please advise, I can raise a PR to amend this.
