### ISSUE TITLE
None JSX references for use in props

### ISSUE THREAD

**Issue by maraisr** [seek-oss/playroom#166]
our design systems has a `<Icon />` component that takes an icon prop, which is an import from a shared icon library that expose svg elements, not components. 

eg: `<Icon icon={HelpCircleIcon} />`, this icon comes from an import `import { HelpCircleIcon } from '@autoguru/icons';`.

Is there a way to expose this to Playroom?

My current solution is to in my frame to go:

```jsx
import * as Icons from '@autoguru/icons';

global.Icons = Icons;

export default ({ theme, children }) => (/* things */);
```

which has worked, just seems a little strange that this is no longer just a frame?

**Comment by michaeltaranto** [comment]
I would suggest re-exporting all the available icons from your components file so they are available. Something like:

```tsx
export * from '@autoguru/icons';
```

**Comment by maraisr** [comment]
Thanks for that @michaeltaranto. Ill try this, and let you know! Cheers ❤️

**Comment by maraisr** [comment]
This worked quite well thanks @michaeltaranto.
