### ISSUE TITLE
playroom with styled-components, gatsby and svgr

### ISSUE THREAD

**Issue by andrelandgraf** [seek-oss/playroom#175]
Thanks so much for playroom, I would love to try it out on my own project!

I tried the following custom webpack config:

```
module.exports = {
  components: './src/components',
  outputPath: './playroom-static',
  frameComponent: './.playroom',
  exampleCode: '<Button label="Welcome" />',
  openBrowser: false,
  webpackConfig: () => ({
    module: {
      rules: [
        {
          test: /\.(js|jsx|ts|tsx)$/,
          include: __dirname,
          exclude: [/node_modules\/(?!(gatsby)\/)/],
          use: {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env', '@babel/preset-react'],
              plugins: [
                '@babel/plugin-proposal-class-properties',
                'babel-plugin-remove-graphql-queries',
                'babel-plugin-styled-components',
              ],
            },
          },
        },
        {
          test: /\.svg$/,
          use: ['@svgr/webpack', 'url-loader'],
        },
      ],
    },
    resolve: {
      mainFields: ['browser', 'module', 'main'],
    },
  }),
};
```

Most of it comes from the [Gatsby documentation](https://www.gatsbyjs.org/docs/visual-testing-with-storybook/) on how to setup storybook, but apparently the `babel-plugin-remove-graphql-queries` does not work since I receive the following error:

```
The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
```

Do you know any workaround for that? Any support appreciated!

**Comment by askoufis** [comment]
This is a bit hard to debug without a minimal reproduction. Also I'm not sure if gatsby documentation on setting up visual testing with storybook is the best thing to reference, unless you're actually using gatsby, which you haven't specified.

Going to close this one as it's quite old, but feel free to re-open with a reproduction if this is still an issue.
