### ISSUE TITLE
Initial brands and screen sizes config

### ISSUE THREAD

**Issue by lauriejones** [seek-oss/playroom#176]
### Feature request

Similar to how you can provide the initial example code via config, I think it would be great to be able to specify the initially enabled brands and screen sizes.

We have one theme that is the primary brand, and then 8 others that are very much secondary. I'd love to be able to set just the primary brand to checked initially to give it focus for the first impression.

**Comment by askoufis** [comment]
Implemented in https://github.com/seek-oss/playroom/pull/305.
