### ISSUE TITLE
User baseUrl for local development

### ISSUE THREAD

**Issue by AndrewLeedham** [seek-oss/playroom#177]
It seems strange to me that `baseUrl` is excluded from the config when running playroom locally (https://github.com/seek-oss/playroom/blob/master/lib/start.js#L8). Is there a reason for this?
I was expecting the local development version to be served from the `baseUrl` the same as the development version. E.g `http://localhost:9000/playroom/` and `https://example.com/playroom/`.

**Comment by BrunnerLivio** [comment]
I introduced baseUrl to playroom. Personally I did not see a reason why you'd want to have a baseUrl locally? What is the motivation behind that?

**Comment by AndrewLeedham** [comment]
I am using playroom along-side a gatsby site, and want to proxy the `/playroom`  requests there to playroom which is hosted on a different port (see https://www.gatsbyjs.org/docs/gatsby-config/#proxy). So the URL structure is the same in development and production.

**Comment by AndrewLeedham** [comment]
This is no longer relevant for the way I am doing things. Using storybook with the playroom add-on now.
