### ISSUE TITLE
Can't get build to output files

### ISSUE THREAD

**Issue by loliver** [seek-oss/playroom#19]
Hi again,

Everything is working with `yarn run playroom:start` but I can't get `yarn run playroom:build` to output actual files, have my `outputPath` set to `'./dist/playroom'` and my `webpackConfig` is as per below:

```JavaScript
  webpackConfig: () => ({
    module: {
      rules: [
        {
          test: /\.js$/,
          loader: 'babel-loader',
          query: {
            plugins: ['lodash'],
            presets: [
              '@babel/preset-react',
              [
                '@babel/preset-env',
                {
                  targets: ['last 2 versions', 'ie >= 11']
                }
              ]
            ]
          },
          exclude: [
            /node_modules\/(?!(@anz)\/).*/
          ]
        },
        {
          test: /\.(otf|ttf|eot|woff(2)?)(\?[a-z0-9=&.]+)?$/,
          loader: 'file-loader'
        },
        {
          test: /\.(jpe?g|png|gif|svg|ico)$/,
          loader: 'file-loader?name=assets/[name].[ext]',
          exclude: '/node_modules/'
        }
      ]
    },
    resolve: {
      extensions: ['.js', '.jsx', '.json']
    }
  })
```

Anything obvious in there that I've missed? I've looked at the examples again today but it seems to work similarly to them.

**Comment by markdalgleish** [comment]
Ah, I've been meaning to fix this massive oversight with build errors not being logged to the terminal. Should be cleared up with this: https://github.com/seek-oss/playroom/pull/20

**Comment by markdalgleish** [comment]
Give v0.4.2 a try, you should hopefully see some error messages now.

**Comment by loliver** [comment]
A+ turnaround time, haha.

I am seeing a few things around babel-loader probably being out of date which is feeding my feelings that I should just burn our design systems website to the ground and start again. Our current one is built on a super old version of the AtlasKit site and uses old everything.

Will close this now as it's given me a trail of breadcrumbs to follow, cheers.

**Comment by loliver** [comment]
Moved it outside the website to use our actual design system dependencies (babel 7 et al) and it worked flawlessly this time, cheers.
