### ISSUE TITLE
[Feature Request] New option to pass forward to react-docgen-typescript

### ISSUE THREAD

**Issue by AndrewLeedham** [seek-oss/playroom#194]
It would be useful to have a config option in `playroom.config.js` which passes forward to https://github.com/styleguidist/react-docgen-typescript#options

**Comment by AndrewLeedham** [comment]
Looks like https://github.com/seek-oss/playroom/pull/130 would resolve this :)

**Comment by michaeltaranto** [comment]
Closed by https://github.com/seek-oss/playroom/pull/232
