### ISSUE TITLE
Running Playroom this morning caused some whacko styles?

### ISSUE THREAD

**Issue by maraisr** [seek-oss/playroom#199]
Running Playroom seems to put frames inside frames?

![image](https://user-images.githubusercontent.com/599459/94754106-a79d0380-03d3-11eb-8251-ed1d9a9ce7f8.png)

**Comment by maraisr** [comment]
Further update, looks to be an issue with it in Firefox.

![image](https://user-images.githubusercontent.com/599459/94984722-82a2bf00-0592-11eb-87cd-6c7bf2c197c4.png)

**Comment by MyGuySi** [comment]
Yeah I've noticed this recently but can't actually put my finger on when it started happening. I've been using Firefox for months without issue so this has only been happening recently for me.
