### ISSUE TITLE
Playroom turns code into base64 garbage, happens randomly

### ISSUE THREAD

**Issue by jimmymarks** [seek-oss/playroom#205]
![Screen Shot 2020-12-02 at 11 37 55 AM](https://user-images.githubusercontent.com/7795474/100902535-f712b500-3492-11eb-89fb-50980028fd28.png)

I keep getting this error at random on our Playroom instance. Doesn't do it for every Playroom link, but it happens often enough that I'm opening this issue. 

The react error in full: 

![Screen Shot 2020-12-02 at 11 38 27 AM](https://user-images.githubusercontent.com/7795474/100902633-0f82cf80-3493-11eb-8646-d0b8a40cf707.png)

Anyone else noticing this? Had this happen? Have some insight?

**Comment by crswll** [comment]
This happens to me when I click a url that isn't fully "linked" properly. Like with Bear (notes app) I'll post some links as ideas in there  and it'll only auto link like half the URL. That might be happening to you?

**Comment by jimmymarks** [comment]
@crswll Yeah, that's pretty much what it was. Thanks for commenting!
