### ISSUE TITLE
Update logo for GitHub darkmode

### ISSUE THREAD

**Issue by ScopeyNZ** [seek-oss/playroom#213]
The logo on the readme can't be read when GitHub is in dark mode:

![image](https://user-images.githubusercontent.com/3260989/106058928-c754e780-60a6-11eb-9cf7-7361b0a5ff10.png)

**Comment by michaeltaranto** [comment]
Yeah i feel you on this one, i had a quick look a while ago, are you aware if there is any way to flip logo image based on colour mode? I couldnt find anything last time.

**Comment by ScopeyNZ** [comment]
You know, it's pretty coincidental that we've just been battling this issue with our own repos when I stumbled across one of @markdalgleish's talks that brought me here.

We've not been able to get it to work with `fill="currentColor"`, and while we can get it to work with the browser dark mode APIs, that reflects your system settings, not GitHub's setting.

We've just gone to using a backgrounds again like back in 2000 🤷

**Comment by michaeltaranto** [comment]
I tried a bunch of things, `currentColor`, relying on cascading styles (trying to at least to get it working on web, but still failed), even tried nested documents using the [css in readme hacks](https://github.com/sindresorhus/css-in-readme-like-wat), still nothing.

**Comment by maraisr** [comment]
One compromise I have made for this, is to give the logo a stroke; see https://github.com/maraisr/diary @ScopeyNZ

**Comment by ScopeyNZ** [comment]
Thanks for the suggestion. We did consider this with our repos but a stroke doesn't really work with our brand unfortunately :(

**Comment by maraisr** [comment]
Ya, doesnt always work. But was a compromise. [xstate](https://github.com/davidkpiano/xstate) got a tad funky with its as well.

**Comment by ScopeyNZ** [comment]
🙉
