### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by loliver** [seek-oss/playroom#215]
Hi all,

Was wondering whether anyone has had any luck getting Playroom to fire up in a Webpack 5 environment?

We run Playroom in the same repo as Gatsby as it's part of the same GitHub Pages site and I haven't been able to get it to work either with specific resolutions or without.

Can provide specific error messages if needed, but was hoping someone from the community already had steps documented for how they got it running.

As always, thanks for the great piece of software.

Cheers!

**Comment by michaeltaranto** [comment]
Closed by https://github.com/seek-oss/playroom/pull/218
