### ISSUE TITLE
Hard to Reset

### ISSUE THREAD

**Issue by hipstersmoothie** [seek-oss/playroom#22]
When developing the playroom it is really hard to reset the the code to the exampleCode. It would be nice if there was a sure fire way of resetting the playroom instance. Refreshing doesn't do anything because of the URL. but clearing the URL doesn't seems to work either.

EDIT: You can usually reset the state by deleting all the code and refreshing, but I seemed to be in a state where even doing that didn't reset the code

**Comment by siddhant1** [comment]
Will try to resolve this !

**Comment by michaeltaranto** [comment]
Clearing and refreshing should return you to the example code. There may have been a localstorage bug that was breaking this previously. Feel free to open if still an issue.

**Comment by jonmilner** [comment]
Hey all, I can't figure out how you're supposed to reset playroom. I'm running locally, and can't seem to reset the code back to default unless I simultaneously clear all site data and remove the param in the address bar. Is it supposed to be simpler, or am I missing something obvious?
