### ISSUE TITLE
Playroom font size in Safari (Big Sur)

### ISSUE THREAD

**Issue by yceballost** [seek-oss/playroom#228]
Hi guys

I detected that the font size in Safari using Mac OS Big Sur is smaller than other version of Mac OS in the entire playroom framework.

Anyone has the same problem?

Thanks!

**Comment by askoufis** [comment]
We're not setting `font-size` on a per-OS basis anyway, so perhaps it was a fallback font issue or something. Can't reproduce this anymore, at least on MacOS Sonoma.
