### ISSUE TITLE
Props completion empty on Sprinkles responsive props

### ISSUE THREAD

**Issue by jimmeyer-els** [seek-oss/playroom#229]
Hi Seek team.

Thanks for creating playroom.

It looks like the conditional responsive props typings from Sprinkles breaks the completion various places in Playroom.

A reproduction example can be seen in Braid for `padding` at https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF4AdEagPkuM0yQBUZ0AXWgOQk0gC22ADYwOhCI0k58RMkgD0bTvWKK06WiAA0IDgAsYAmAGcEAbRC48YEAF1dAd0JQDZ%2BOYDMAJgAM2gEZfbwAWOwBfIA

**Comment by michaeltaranto** [comment]
Thanks for reporting, this is fixed by #232, but will be released when braid itself takes in the playroom update.

Closed by https://github.com/seek-oss/playroom/pull/232
