### ISSUE TITLE
Shared links are broken

### ISSUE THREAD

**Issue by yceballost** [seek-oss/playroom#253]
Hi guys,

With the last version share link is changed from `/preview#` to `/preview/#`

[Old link](https://mistica-web.vercel.app/playroom/preview#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF5gBGANgF8A+AHWM0yQGUAXXMAa0wBnPGBiUALAAZGLNm1QBXLlwjEACgCdCAW1waAnplWaYgwZQAUASkzkGmYHUYBBMF0KqkAehRKV6rV0DZlZ2L25ePhDvNHQQkAAaEC4ACxhtOEQAWQgAN0JBHg0QOiA)
[New link](https://mistica-web.vercel.app/playroom/preview/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF5gBGANgF8A+AHWM0yQGUAXXMAa0wBnPGBiUALAAZGLNm1QBXLlwjEACgCdCAW1waAnplWaYgwZQAUASkzkGmYHUYBBMF0KqkAehRKV6rV0DZlZ2L25ePhDvNHQQkAAaEC4ACxhtOEQAWQgAN0JBHg0QOiA)

This change generate broken links with a lot of links shared.

Would be nice to still allowing the old way.

**Comment by michaeltaranto** [comment]
Hey, the last version was a header change for the webpack dev server. Can you confirm the versions that you are upgrading from and to please

**Comment by yceballost** [comment]
Sure, we upgraded from `0.25.0` to `0.27.9`

**Comment by michaeltaranto** [comment]
Yeah ok, that's quite a few versions. I'll have a poke around and see if anything jumps out.
