### ISSUE TITLE
Windows machine giving Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]:  from version 0.33.0 upwards

### ISSUE THREAD

**Issue by tomclague** [seek-oss/playroom#307]
Hi,
I am running playroom from a windows machine, and have noticed from version 0.33.0 upwards, 'playroom start' gets error:

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

Working fine with previous versions (i can revert to 0.32.1 for now). Please investigate.
Windows 10 Enterprise
Node 18.9.0

**Comment by duncanhunter** [comment]
I also have this issue on windows and can confirm downgrading to 0.32.1 resolved the error.
