### ISSUE TITLE
Unable to build playroom without a favicon

### ISSUE THREAD

**Issue by jordanoverbye** [seek-oss/playroom#311]
I'm unable to run `playroom build` after upgrading to `0.34.1`. I'm getting the following error:

```
Error: HtmlWebpackPlugin: could not load file /path/to/repo/images/favicon.png
- index.js:494      [repo]/[html-webpack-plugin]/index.js:494:35     error Command failed with exit code 1.
```

This seems to have been caused by PR #309

If I create a `images/favicon.png` file everything works correctly, but this seems unexpected for a patch release.

**Comment by mrm007** [comment]
@jordanoverbye does [this snapshot](https://github.com/seek-oss/playroom/actions/runs/7635268557) work for you?
