### ISSUE TITLE
[Feature Request] Accessibility tool integrated in playroom

### ISSUE THREAD

**Issue by yceballost** [seek-oss/playroom#317]
This is a really nice to have, but anyway, I throw the idea...

I was thinking to have the possibility to have a tab that show a live accessibility test using Axe-Core or Pa11y (or [combined](https://github.com/abbott567/axe-core-vs-pa11y))

I think this feature helps to make accessibility more present when prototyping solutions, be it with components from a library or custom creations with primitives from that library.

The visualization can be similar like this idea https://github.com/seek-oss/playroom/issues/255, a new tab with the results

**Comment by askoufis** [comment]
Thanks for the request!

Playroom is primarily focused on prototyping. Accessibility tools like the ones you've linked are more focused towards catching issues during development/CI.

Additionally, the browser dev tools, browser extensions and other third-party tools can already surface accessibility issues in Playroom for you.
