### ISSUE TITLE
Upgrade to codemirror2

### ISSUE THREAD

**Issue by hipstersmoothie** [seek-oss/playroom#32]
Every time I install I get this 

```
warning "playroom > react-codemirror@1.0.0" has incorrect peer dependency "react@>=15.5 <16".
warning "playroom > react-codemirror@1.0.0" has incorrect peer dependency "react-dom@>=15.5 <16".
```

`react-codemirror` doesn't seem to have been published in 2 years and depends on an old version of react. `playroom` itself uses 

```json
    "react-dom": "^16.5.2",
```

So this is where the mismatch comes from. A possible solution would be to upgrade to https://www.npmjs.com/package/react-codemirror2, which allows newer versions of react

```json
    "react": ">=15.5 <=16.x",
```

**Comment by siddhant1** [comment]
Will take a look at this!

**Comment by hipstersmoothie** [comment]
Idk if it’s worth it m. Both react code mirror projects seem unmaintained

**Comment by kaelig** [comment]
https://github.com/scniro/react-codemirror2 is great (we use it on polaris.shopify.com), way more up to date than `react-codemirror`.

**Comment by hipstersmoothie** [comment]
yessssss. goodbye peer dep warnings
