### ISSUE TITLE
Playroom favicon is not customizable

### ISSUE THREAD

**Issue by marcoskolodny** [seek-oss/playroom#320]
Hello!

I was trying to add a custom favicon to my Playroom website, but I couldn't make it work. After digging into the code, I've noticed that in [this PR](https://github.com/seek-oss/playroom/pull/309) you are forcing the icon to be the playroom logo.

I believe the playroom logo is nice to have, but the favicon should be customizable. I fully agree with [this comment](https://github.com/seek-oss/playroom/pull/309#discussion_r1430926743) in the PR. Why not allowing users to pass their own favicon through playroomConfig or through the public folder, and using the playroom logo as fallback if the user didn't pass one?

**Comment by felixhabib** [comment]
Thanks for the request!

Currently we don't see the value in offering a custom favicon, as the current favicon helps distinguish Playroom tabs from other browser tabs. As such, it does not seem worth the API complexity to add this feature. 

However, if we see a valid use for this feature, we will look to revisit this.
