### ISSUE TITLE
Duplicated components in viewport but not in code panel 😣

### ISSUE THREAD

**Issue by yceballost** [seek-oss/playroom#368]
I guys, I found something weird.

When you select snippet in a fast way, the snippet is placed in the code panel but in the viewport you can see this snippet duplicated.

A video to show this behavior. This video is made with **Braid playroom**. I found it in our playroom implementation but I confirm that is happening in other playrooms. 

https://github.com/user-attachments/assets/32cd5887-3ca4-423b-8dc4-52be084f61e0

In the video I was using Arc as a browser (in incognito mode to avoid problems with extensions), but also is happening in Safari

**Comment by felixhabib** [comment]
Thanks for the issue! Playing with this on a couple machines and browsers, I'm unable to replicate this behaviour. Does this occur consistently for you, and only when selecting snippets with the cursor? I appreciate any additional info.

**Comment by yceballost** [comment]
Yes, only when I open snippet panel with cursor and select a snippet "quite" fast. 

My steps to try to replicate is:
1. Put a snippet
2. Delete this snippet
3. Open snippet panel with cursor and select one (fast)

I tried the same in a Macbook Pro with Chrome and Sonoma (14.6.1) and I also can replicate the issue.

**Comment by felixhabib** [comment]
Thanks for this! I was able to replicate the issue and have found a fix

**Comment by yceballost** [comment]
thanks for the quick fix!! 🥰🥰
