### ISSUE TITLE
Resizing the editor doesn't work with re-resizable

### ISSUE THREAD

**Issue by HalvorHaugan** [seek-oss/playroom#373]
The version of re-resizable is set to "^6.9.9" in package.json. Package managers will install the newest minor version (6.10.0 in the time of writing). Version 6.10.0 introduces a change that breaks the resize feature in Playroom. The problem is that the div that has the resize feature has been moved in the DOM so that it no longer appears on top. ([I believe this is the change that causes it](https://github.com/bokuweb/re-resizable/pull/827/files#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R982).)

It can be fixed by adding this to `<Resizable>` in Playroom.tsx: `handleStyles={{ top: { zIndex: 1 }, left: { zIndex: 1 } }}`

**Comment by felixhabib** [comment]
Thanks a lot for flagging this!
