### ISSUE TITLE
Compatibility with react-pose

### ISSUE THREAD

**Issue by puregarlic** [seek-oss/playroom#45]
I'm running into an issue with refs while trying to use a `react-pose` component in Playroom. I've create a reproduction repo here: https://github.com/puregarlic/playroom-pose-compat

Am I missing something? I'm not really sure why it works in a normal environment but not in Playroom.

**Comment by bradbarrow** [comment]
Facing the same challenge. 

The point of difference I've narrowed down to is that **outside** of playroom, the `ref` here IS an `instanceof Element`.

and **inside** Playroom it is NOT an `instanceof Element`.

https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/components/PoseElement/index.tsx#L169

https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/components/PoseElement/index.tsx#L188

A potentially helpful debug log: 

![image](https://user-images.githubusercontent.com/1264276/52056350-1b12c000-25b6-11e9-9daf-31cd87ef3b93.png)

You can see that `ref` is indeed an `HTMLDivElement` but apparently that doesn't make it an instance of `Element` in this case.

Also, on a single visit to playroom...the ref get's overridden to null:

![image](https://user-images.githubusercontent.com/1264276/52056425-52816c80-25b6-11e9-9deb-f6276bcd8987.png)

And lastly a debug log from outside of Playroom:

![image](https://user-images.githubusercontent.com/1264276/52056448-675e0000-25b6-11e9-85a5-eb2377423b14.png)

I wonder if the scope-eval step in Playroom is mucking about with the refs?

I'll try to keep digging on this tomorrow

**Comment by bradbarrow** [comment]
Some further observations of the lifecycle of a ref in Playroom as you edit

![image](https://user-images.githubusercontent.com/1264276/52093581-cc920f80-260f-11e9-850f-bae10b25e7ac.png)

**Comment by bradbarrow** [comment]
This may be naive but I think the gist of this is that the instanceof checks are failing because the ref IS an Element but it's an instance of Element in the IFrame which is it's own DOM. 

So on the surface it seems identical but there's actually more than one DOM at play?

**Comment by ryanhobsonsmith** [comment]
@bradbarrow just hit the same problem. Was able to get it working by patching like:

**Comment by ryanhobsonsmith** [comment]
@bradbarrow just hit the same problem with iframe / react-pose, was able to get things working by patching react-pose and stylefire to use checks like the following:
```javascript
ref instanceof ref.ownerDocument.defaultView.Element
```
so that it used the window/global object that the node belonged to for this instance check. I only needed a quick fix for a component style guide I was putting together so I haven't extensively tested this approach but so far I haven't noticed any issues.

**Comment by markdalgleish** [comment]
Should be fixed in v0.9.0.
