### ISSUE TITLE
React Hooks support

### ISSUE THREAD

**Issue by loliver** [seek-oss/playroom#49]
Hey there,

We're migrating all of our Recompose based components to Hooks over the next week or so and I've noticed we get the good old `Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)` error when using hooks based components.

Happy to supply a PR once I'm finished our refactoring work.

Cheers.

**Comment by loliver** [comment]
I'd love some help on it, not particularly experienced in this level of digging in to the internals of React and playroom isn't high on the priority list as far as my line managers are concerned unfortunately. The latest error boundaries work has helped tremendously but as soon as I try the basic update dependencies approach and use `yarn link` nothing works anymore.

**Comment by loliver** [comment]
@cneeson check out #58 and see if it works for your components.

**Comment by cneeson** [comment]
Works well for me @loliver, thanks for investigating!
