### ISSUE TITLE
material-ui example yields Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by mpoppins** [seek-oss/playroom#62]
No doubt some simple error but if I run yarn in the root dir then in the material-ui example dir and do a yarn start I get a Cannot read property 'document' of undefined at line: 

insertionPoint: props.frameWindow.document.head

am i making a simple error?

**Comment by denesreyes** [comment]
Run into the same issue, removing that line of code seems to fix the issue.

As to why it was failling I am not sure, but inspecting the props, there is no frameWindow object being passed into it. Hence the runtime error.
