### ISSUE TITLE
Styled-jsx support?

### ISSUE THREAD

**Issue by damianfabian** [seek-oss/playroom#67]
Hi guys, I'm trying to use styled-jsx with playroom and don't know really well where to start to make this possible. is there any doc that I can read to make it happen? Thanks!

**Comment by michaeltaranto** [comment]
I would suggest looking at the docs for `styled-jsx`. If you can configure a component library to use it, all playroom needs is the webpack config that the components needs, and the path to the file that exports the components.

Hope that helps.
