### ISSUE TITLE
SVG support webpack config

### ISSUE THREAD

**Issue by mikeq** [seek-oss/playroom#68]
Hi,

I was trying to have a component that imports an svg and then displays that within the component, svg isn't handled by default in playroom webpack config so thought it would just be a case of including it in custom config and that would be merged with playrooms webpack config

```js
  webpackConfig: () => ({
    module: {
      rules: [
        {
          test: /\.svg$/,
          loader: 'svg-inline-loader',
        },
      ],
    },
  }),
```

But this seems to overwrite the playroom webpack config and errors appear about being unable to handle .js files

**Comment by damianfabian** [comment]
I was able to do it using this configuration, this might help you

```
webpackConfig: () => ({
      module: {
        rules: [
          {
            test: /\.js$/,
            include: __dirname,
            exclude: /node_modules/,
            use: {
              loader: 'babel-loader',
              options: {
                presets: ['@babel/preset-env', '@babel/preset-react']
              }
            }
          },
          {
            test: /\.svg$/,
            loader: 'svg-inline-loader?classPrefix'
          },
          {
            test: /\.css\.js$/,
            use: [
              {
                loader: 'style-loader'
              },
              {
                loader: 'css-loader',
                options: {
                  modules: true,
                  localIdentName: '[name]__[local]___[hash:base64:7]',
                  importLoaders: 2
                }
              },
              {
                loader: 'css-in-js-loader'
              },
              {
                loader: 'babel-loader',
                options: {
                  presets: ['@babel/preset-env', '@babel/preset-react'],
                  plugins: ['babel-plugin-transform-class-properties']
                }
              },
              
            ]
          },
        ]
      }
    })
```

**Comment by mikeq** [comment]
So you kind of have to replace the entire webpack config?  I thought it was supposed to merge our defined config into the default config?

**Comment by damianfabian** [comment]
I thought the same but did not work. It's working now tho.

**Comment by michaeltaranto** [comment]
There is a [default webpack config](https://github.com/seek-oss/playroom/blob/fa28632b9c64308068bf36fe8207aa741925dd4e/lib/makeDefaultWebpackConfig.js), but providing your own currently [overrides](https://github.com/seek-oss/playroom/blob/fa28632b9c64308068bf36fe8207aa741925dd4e/lib/makeWebpackConfig.js#L145) this to support customising for your component library without the risk of clashing.
