### ISSUE TITLE
Cannot create ErrorBoundary Component

### ISSUE THREAD

**Issue by duttaoindril** [seek-oss/playroom#69]
> Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
> 
> SyntaxError: ErrorBoundary.js: Support for the experimental syntax 'classProperties' isn't currently enabled:
> 
> `static getDerivedStateFromError = error => ({ hasError: true, error });`
> 
> Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

Please tell me how to either add that plugin to the `webpackConfig: () => ({ })` or please add that plugin to the default build - in fact I encourage keeping up to date with CRA's webpack config.

**Comment by michaeltaranto** [comment]
Specifying the `webpackConfig` overrides [the default config[(https://github.com/seek-oss/playroom/blob/edaf6a6037d935064e23c0bf15abdb7b69ca5044/lib/makeDefaultWebpackConfig.js). So you could copy the default, add the plugin and specify that in your config.

Hope that helps.
