### ISSUE TITLE
Props autocomplete for components with declaration files

### ISSUE THREAD

**Issue by eps1lon** [seek-oss/playroom#70]
I was super impressed by the presentation at React Amsterdam 2019 and immediately started playing with some ideas. After [some little experiments](https://github.com/eps1lon/material-ui-playroom) I was already pretty satisfied. The biggest issue right now is missing props autocomplete. The problem is that the props are not defined in an actual TypeScript file but in a declarations file. It seems like  react-docgen-typescript can't detect components in those properly.

It's not really important to get this working from the typescript declarations. Those are pretty complicated and we already have this information available from another source. My question is if I should rather work on making react-docgen-typescript work with declaration files or work on an API for playroom so that I can inject prop types from arbitrary sources. Essentially allowing plugins for typescript, flow or prop-types.

**Comment by PinkyJie** [comment]
I also got the same issue, I think the issue now is `react-docgen-typescript` does not support type definition files (https://github.com/styleguidist/react-docgen-typescript/issues/231). The workaround is to compile your ts files with babel-loader with plugin https://github.com/milesj/babel-plugin-typescript-to-proptypes

**Comment by eps1lon** [comment]
No longer using this library
