### ISSUE TITLE
Question regarding component exports

### ISSUE THREAD

**Issue by josefaidt** [seek-oss/playroom#74]
I believe I may be misunderstanding the methods for importing components. I've noticed if I define a components as shown below:

```js
// src/components/Button/Button.js
import React from 'react'
const Button = props => <button {...props} />
export default Button
```

```js
// src/components/Text/Text.js
import React from 'react'
export const Text = props => <p {...props} />
```

and my components file looks like

```js
const Button = require('./Button/Button')
const { Text } = require('./Text/Text')

module.exports = {
  Text,
  Button,
  // etc...
}
```

only the Text component will work. The button component is throwing an error:

```shell
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `RenderCode`.
```

It seems I can use named exports just fine but using a default export gives me an error. Is there a correct way to use a default-exported component? Below are links to the demo repo and a live demo.

## Links

[sample repository](https://github.com/josefaidt/playroom-demo)
[live demo](https://josef-playroom.netlify.com/)

**Comment by pascalduez** [comment]
`const Button = require('./Button/Button').default`?

**Comment by josefaidt** [comment]
Ah @pascalduez that does work. I'm guessing this is a caveat? Minor workaround, but useable. 

I tried adding `@babel/plugin-proposal-export-default-from` in the custom webpack config to no avail.

**Comment by michaeltaranto** [comment]
Looks like you're mixing module types — commonjs in your components file, and es modules in your individual component files. Rather than mix and matching i'd advise using es if you can, eg:
```js
export { default as Button } from './Button/Button';
export { Text } from './Text/Text';
```
Personally i'd then export the `Button` as a named export and drop the need for re-mapping the `default` here too.
