### ISSUE TITLE
Trying out integrations with Typescript, Monaco Editor, React hooks, and React Box (my own thing)

### ISSUE THREAD

**Issue by nksaraf** [seek-oss/playroom#93]
Hi, Firstly thanks for this super awesome tool. I really loved how simple it is and how simply it works. 

I just wanted to share a fork, https://github.com/nksaraf/playroom, that I have been working on for my own use cases. You can see examples of some of the cool things that managed to work in playroom at the end of this comment.

So I integrated the Monaco editor and migrated some of the core Playroom react code to Typescript and hooks because I found it easier to work with. The last and probably the collest thing I was able to make work was being able to use React hooks and that means probably all of React's functionality from the playroom editor. The JSX is still formatted and interpreted correctly even if its has multiple parents tags because we wrap it in a fragment. And no return statement is necessary so its kinda svelte-ish in its look and simplicity. It makes a lot of cool stuff possible. You can also import your own hooks with your components, no additional code is required (probably should add config though). I also have tried useEffect and fetched data all correctly.

All of this works on its own just like the old playroom. But another cool integration that I made is with this library I wrote https://github.com/nksaraf/react-box (not yet published). But its essentially some React primitives (mainly the Box) that wrap functionality from styled-components, styled-system, framer-motion to allow styling and animations declaratively through just props. And with hooks, now writing almost anything should be possible treating the playroom as a functional components. I have deployed this integration at https://playroom.now.sh if anyone wants to give it a try.

Also, if the contributors would want to discuss integrating some of this with the playroom library,  I would love to make a pull request but I probably broke a lot of the CI/CD stuff because I am not well versed on it. (Sorry, I am not certain of what the process for this is because this is my first time contributing to open source).

Also @markdalgleish loved your talk on design systems, would love to hear what you think about some of this.

PS: There are still a lot of any's in my typescript but I was just trying to make it work. I haven't got intellisense to work correctly with the user types in Monaco, but I see a path where the types generated by react-docgen can be put into a .d.ts file and fed into the monaco editor that I did with the React types which worked.

Here are some examples of things that becomes possible. You can directly use the links and play around with the code thanks to the sandboxing and how the creators made the code part of the url!

## React hooks
<img src="https://github.com/nksaraf/playroom/raw/master/images/hooks.gif" alt="Hooks in Playroom Demo" title="Hooks in Playroom Demo" />

[playroom link - hooks](https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABAbUgV2XRgCcAaTVGdAYQgKOIF1MBeTAJRgEMx0A6PJQDK6LkQAUABgCUAbgA6ySGiwBLJcRgBbGIVr0SrTOOmsAfBSr7CJcfhvFzmew0wBqTAEY5ixQB4AITx0dBRnPGJUCGIWeRAABwh1BjjMFAAVLniWYHUwTR09OgcAXzNFTExM+IB6agAbVTAAa0xQzC0IADcYTC4AC24oPn8aoJCUcuRAiAAPTAAzFHQhVQAvGByAJgAWMoBNOj7NPqwMGHjMYBcSEr4-MbmpkBKgA)

## Animation and stlying props with @nksaraf/react-box

<img src="https://github.com/nksaraf/playroom/raw/master/images/animation.gif" alt="Animations with Framer Motion in Playroom Demo" title="Animations with Framer Motion in Playroom Demo" />

[playroom link - animation and styling](https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABAbQwQ3RgBpNUZ0BldAmAXUwF5MAlGPMdAOgFcyqaAFAB0QeEQEoA3EOQyAPACEIADxmZMANzwAnAJZ5k6VA2DBMeeJjMAbGADN0lgAyYAviQBGlm-ceYAjE4urm6uaphg3NqoENoMIgAOELqGMNoi4Umouui6KPEg2jDWBLoaMBnI6igAKngJJgLijAB8pOT8hAL4hK2Y3dS9DEwiYiCYAPyYIh4imJajEuJhVebIugC2NCY9MCst4QASxdYQmADqsdZQAITyAPRKygfIIK5AA)

## Data fetching with useEffect

<img src="https://github.com/nksaraf/playroom/raw/master/images/effect.gif" alt="Data fetching in Playroom Demo" title="Data fetching in Playroom Demo" />

[playroom link - Data fetching](https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABAbQA4QGsYBbFAGk1RnQAVCSUBdTAXkwCUYBDMdAOgCuVAMrou6GAAoAOiHQAnGDDAEIsgJQBuackhos2AJbEuAcxgUqteqWQBJE+eZtOPfkJijxU2Ru3JXXkEqAFEAMzDldElJdVYAPkxgHUxMPQxMRVQBABssNkj0MAALSQADYvR0XFR4AHo6-CIuXEM+SDqWwzqANwAmRpsUOoASYCaGZABfMvUU1Mw+dGKYZEkocS4EzA2xPgArVBRYueQFxeXV9c3tqzoiWwczKV2uPlRceUMJVD4w+RQ6AA+rAwlxcuh1Kdzu1xCVJDB5AD5LdqPdJk9zDIQBotDophQ8ENkIw8cgdAAeOzIXACdDzHpcHICGAscbEqbzFAAYWKXGQ5jZjOZMFR1gex2FLPaAiRq3QABUuPJzPwpTB1JzkHV4pTMaLUPIwGzjM8ppgdToQFMgA)

## Forms with Formik

<img src="https://github.com/nksaraf/playroom/raw/master/images/forms.gif" alt="Forms with Formik Demo" title="Forms with Formik Demo" />

[playroom link - Forms with Formik](https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABMTA3AhgDYCuMqANJgBb7JSEwDCNyA5jJgL6YC8mxqGADEIAJwC2ASwDWACmAAdZJkyTkk9JKIA1IqVTxsSlSuT5xMQwpABldDAAOVGMmvGu5dyhvEARlPRDWQBKXgA+bE4lTmCAbiUlAB4w90SASWQHYiwCEhgeYFz9ADozC24UZlp2ApZ6JhZ2bjL86xbrTAB6FOVMRIAhCAAPTDBiUVQxHmsHCDV7UQ7IQinrXzzigFYABm3rHpNMAAkYQhXsIrJS8xhOAEJUzsGhnsTupRBOIA)

**Comment by nksaraf** [comment]
Here are some examples of becomes possible,
## React hooks
<img src="https://github.com/nksaraf/playroom/raw/master/images/hooks.gif" alt="Hooks in Playroom Demo" title="Hooks in Playroom Demo" />
https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABAbUgV2XRgCcAaTVGdAYQgKOIF1MBeTAJRgEMx0A6PJQDK6LkQAUABgCUAbgA6ySGiwBLJcRgBbGIVr0SrTOOmsAfBSr7CJcfhvFzmew0wBqTAEY5ixQB4AITx0dBRnPGJUCGIWeRAABwh1BjjMFAAVLniWYHUwTR09OgcAXzNFTExM+IB6agAbVTAAa0xQzC0IADcYTC4AC24oPn8aoJCUcuRAiAAPTAAzFHQhVQAvGByAJgAWMoBNOj7NPqwMGHjMYBcSEr4-MbmpkBKgA

## Animation and stlying props with @nksaraf/react-box
<img src="https://github.com/nksaraf/playroom/raw/master/images/animation.gif" alt="Animations with Framer Motion in Playroom Demo" title="Animations with Framer Motion in Playroom Demo" />
https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABAbQwQ3RgBpNUZ0BldAmAXUwF5MAlGPMdAOgFcyqaAFAB0QeEQEoA3EOQyAPACEIADxmZMANzwAnAJZ5k6VA2DBMeeJjMAbGADN0lgAyYAviQBGlm-ceYAjE4urm6uaphg3NqoENoMIgAOELqGMNoi4Umouui6KPEg2jDWBLoaMBnI6igAKngJJgLijAB8pOT8hAL4hK2Y3dS9DEwiYiCYAPyYIh4imJajEuJhVebIugC2NCY9MCst4QASxdYQmADqsdZQAITyAPRKygfIIK5AA

## Data fetching with useEffect
<img src="https://github.com/nksaraf/playroom/raw/master/images/effect.gif" alt="Data fetching in Playroom Demo" title="Data fetching in Playroom Demo" />
https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABAbQA4QGsYBbFAGk1RnQAVCSUBdTAXkwCUYBDMdAOgCuVAMrou6GAAoAOiHQAnGDDAEIsgJQBuackhos2AJbEuAcxgUqteqWQBJE+eZtOPfkJijxU2Ru3JXXkEqAFEAMzDldElJdVYAPkxgHUxMPQxMRVQBABssNkj0MAALSQADYvR0XFR4AHo6-CIuXEM+SDqWwzqANwAmRpsUOoASYCaGZABfMvUU1Mw+dGKYZEkocS4EzA2xPgArVBRYueQFxeXV9c3tqzoiWwczKV2uPlRceUMJVD4w+RQ6AA+rAwlxcuh1Kdzu1xCVJDB5AD5LdqPdJk9zDIQBotDophQ8ENkIw8cgdAAeOzIXACdDzHpcHICGAscbEqbzFAAYWKXGQ5jZjOZMFR1gex2FLPaAiRq3QABUuPJzPwpTB1JzkHV4pTMaLUPIwGzjM8ppgdToQFMgA

**Comment by nksaraf** [comment]
Here are some examples of becomes possible. You can directly use the links and play around with the code thanks to how the creators made the code part of the url!

## React hooks
<img src="https://github.com/nksaraf/playroom/raw/master/images/hooks.gif" alt="Hooks in Playroom Demo" title="Hooks in Playroom Demo" />
[playroom link](https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABAbUgV2XRgCcAaTVGdAYQgKOIF1MBeTAJRgEMx0A6PJQDK6LkQAUABgCUAbgA6ySGiwBLJcRgBbGIVr0SrTOOmsAfBSr7CJcfhvFzmew0wBqTAEY5ixQB4AITx0dBRnPGJUCGIWeRAABwh1BjjMFAAVLniWYHUwTR09OgcAXzNFTExM+IB6agAbVTAAa0xQzC0IADcYTC4AC24oPn8aoJCUcuRAiAAPTAAzFHQhVQAvGByAJgAWMoBNOj7NPqwMGHjMYBcSEr4-MbmpkBKgA)

## Animation and stlying props with @nksaraf/react-box
<img src="https://github.com/nksaraf/playroom/raw/master/images/animation.gif" alt="Animations with Framer Motion in Playroom Demo" title="Animations with Framer Motion in Playroom Demo" />
[playroom link](https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABAbQwQ3RgBpNUZ0BldAmAXUwF5MAlGPMdAOgFcyqaAFAB0QeEQEoA3EOQyAPACEIADxmZMANzwAnAJZ5k6VA2DBMeeJjMAbGADN0lgAyYAviQBGlm-ceYAjE4urm6uaphg3NqoENoMIgAOELqGMNoi4Umouui6KPEg2jDWBLoaMBnI6igAKngJJgLijAB8pOT8hAL4hK2Y3dS9DEwiYiCYAPyYIh4imJajEuJhVebIugC2NCY9MCst4QASxdYQmADqsdZQAITyAPRKygfIIK5AA)

## Data fetching with useEffect
<img src="https://github.com/nksaraf/playroom/raw/master/images/effect.gif" alt="Data fetching in Playroom Demo" title="Data fetching in Playroom Demo" />
[A](https://playroom.now.sh/#?code=N4Igxg9gJgpiBc4IDsDOAXABAbQA4QGsYBbFAGk1RnQAVCSUBdTAXkwCUYBDMdAOgCuVAMrou6GAAoAOiHQAnGDDAEIsgJQBuackhos2AJbEuAcxgUqteqWQBJE+eZtOPfkJijxU2Ru3JXXkEqAFEAMzDldElJdVYAPkxgHUxMPQxMRVQBABssNkj0MAALSQADYvR0XFR4AHo6-CIuXEM+SDqWwzqANwAmRpsUOoASYCaGZABfMvUU1Mw+dGKYZEkocS4EzA2xPgArVBRYueQFxeXV9c3tqzoiWwczKV2uPlRceUMJVD4w+RQ6AA+rAwlxcuh1Kdzu1xCVJDB5AD5LdqPdJk9zDIQBotDophQ8ENkIw8cgdAAeOzIXACdDzHpcHICGAscbEqbzFAAYWKXGQ5jZjOZMFR1gex2FLPaAiRq3QABUuPJzPwpTB1JzkHV4pTMaLUPIwGzjM8ppgdToQFMgA)

**Comment by jasonmendes** [comment]
@nksaraf This is really neat! I was looking how to use Playroom with TypeScript and Hooks.

**Comment by marlonpp** [comment]
hey @nksaraf, I was curious to see your fork but couldn't find it.
Is it still available?

**Comment by karanshah229** [comment]
@michaeltaranto @markdalgleish
Can we get `hooks` working in playroom out of the box.
