### ISSUE TITLE
Configuring how image paths are resolved in Playroom

### ISSUE THREAD

**Issue by liamdanielduffy** [seek-oss/playroom#99]
Hi,

1. I use Next.js for my application, so  I need to write `<img src="/image.jpeg">` and `background-image: url("/image.jpeg")` to display an image stored at `public/image.jpeg` relative to the project root. ([reference to docs on this](https://nextjs.org/docs#static-file-serving-eg-images))

2. However, Playroom appears to resolve `<img>` `src` paths and `background-image: url(...)` paths from the root of the project. I need to use either `<img src="public/image.jpeg"/>` or `background-image: url('public/image.jpeg')` to display the image stored at `public/image.jpeg`

3. This makes the paths for my images in the Playroom environment incompatible with the paths that images need to resolve properly in the Next.js environment. 

Ideally, I would like all image paths starting with `/` to resolve to paths starting with `/public` in the Playroom environment. For example, `/image.jpeg` would resolve to `/public/image.jpeg`

What's the best way to accomplish this?

**Comment by michaeltaranto** [comment]
Hey 👋 
Sounds like you need to configure a webpack loader to handle images, the default config provided does not have any opinions on images. You can pass this loader config into playroom via the `webpackConfig` option.
